servicereg/website/serviceprovider/urls.py
from django.conf.urls import url
from . import views

app_name = 'serviceprovider'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login_user, name='login_user'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^save_state/$', views.save_state, name='logout_user'),
    # url(r'^ordersdetail/$', views.index, name='index'),
    url(r'^(?P<serviceprovider_id>[0-9]+)/$', views.serviceProviderDetails, name='sd'),
    url(r'^orderdetails/$', views.index, name='index'),
    url(r'^orderdetails/(?P<order_id>[0-9]+)/$', views.orderDetails, name='orderdetails'),
    url(r'^orderdetails/itemdetails/(?P<item_id>[0-9]+)/$', views.itemDetails, name='itemdetails'),
    url(r'^sporderdetails/(?P<serviceprovider_id>[0-9]+)/$', views.spOrderDetails, name='orderdetails'),
]

servicereg/website/website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # url(r'^serviceprovider/', include('serviceprovider.urls')),
    # path('admin/', admin.site.urls),
    url(r'^serviceprovider/', include('serviceprovider.urls')),
    # url(r'^', include('serviceprovider.urls')),
    url(r'^admin/', admin.site.urls),
]

servicereg/website/serviceprovider/models.py
from django.db import models
from django.urls import reverse

class Orders(models.Model):
    orderId = models.IntegerField(primary_key=True)
    customerId = models.IntegerField()    
    fulfilled = models.BooleanField(default=False)
    latitude = models.FloatField(default=0.0)
    longitude = models.FloatField(default=0.0)
    # Order Type
    # 1. Groceries
    # 2. Ambulance
    # 3. Medical Supply
    # 4. Water Supply
    orderType = models.IntegerField(default=0)
    def get_absolute_url(self):
        return reverse('serviceprovider:orderdetails', kwargs={'pk':self.pk})
    def __str__(self):
        s=str(self.orderId) + ' - ' + str(self.customerId) + ' - ' + str(self.fulfilled)+'-'
        s+=str(self.latitude) + ' - ' + str(self.longitude) + ' - ' +  str(self.orderType)
        return s

class Items(models.Model):
    itemId = models.IntegerField(primary_key=True)
    oId = models.ForeignKey(Orders, on_delete=models.CASCADE)
    provider_id = models.IntegerField()   
    # fulfilled = models.BooleanField(default=False)

    def __str__(self):
        return str(self.itemId) + ' - ' + str(self.oId) + ' - ' + str(self.provider_id)

class Service(models.Model):
    serviceProviderId = models.IntegerField(primary_key=True)
    serviceProviderName = models.CharField(max_length=250, default="Groceries")
    # Service Provider Type
    # 1. Groceries
    # 2. Ambulance
    # 3. Medical Supply
    # 4. Water Supply
    serviceProviderType = models.IntegerField(default=1)    
    latitude = models.FloatField(default=0.0)
    longitude = models.FloatField(default=0.0)
    loggedIn = models.BooleanField(default=False)
    def __str__(self):
        s = str(self.serviceProviderName) + ' - ' + str(self.serviceProviderType) + ' - '
        s+= str(self.latitude) + ' - ' + str(self.longitude) + ' - ' + str(self.loggedIn)
        return s

class Order_Dispatch(models.Model):
	service_id=models.ForeignKey(Service, on_delete=models.CASCADE)
	order_id=models.ForeignKey(Orders, on_delete=models.CASCADE)

servicereg/website/serviceprovider/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

servicereg/website/serviceprovider/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime
from .models import Orders, Items, Service, Order_Dispatch
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserForm
from django.db.models import Q
from django.template import loader
from django.db.models import F, Func
from django.views.decorators.csrf import csrf_exempt
import json



def index(request):
    now = datetime.datetime.now()

    # html = "<html><body>It is now %s.</body></html>" % now
    # # return HttpResponse(html)
    all_orders = Orders.objects.all()
    # template = loader.get_template('')
    context= {'allorders': all_orders}
    return render(request, 'serviceprovider/orderlist.html', context)
    # html='<html><body>'
    # for order in all_orders:
    #     print(str(order.orderId))
    #     url = '/serviceprovider/'+str(order.orderId)+'/'
    #     html+= '<a href-"'+url+'">'+order.orderId+'</a><br>'
    # html+='</body></html>'
    # html = "<html><body>It is now %s.</body></html>" % now
    # return HttpResponse(html)
    # return render(request, 'serviceprovider/test.html')

def orderDetails(request, order_id):
    # html = "<html><body>"+ str(order_id)+"</body></html>"
    # album = get_object_or_404(Orders, pk=order_id)
    # return render(request, 'serviceprovider/t2.html')
    # return render(request, 'serviceprovider/t2.html', {'album': album})
    # return HttpResponse("<h2>Details for album id "+str(order_id)+"</h2>")
    order = get_object_or_404(Orders, pk=order_id)
    items = Items.objects.all().filter(oId=order_id)
    return render(request, 'serviceprovider/orderdetails.html', {'order': order, 'allitems':items})

def itemDetails(request, item_id):
    items = get_object_or_404(Items, pk=item_id)
    return render(request, 'serviceprovider/itemdetails.html', {'items': items})

def serviceProviderDetails(request, serviceprovider_id):
    sprovider = get_object_or_404(Service, pk=serviceprovider_id)
    return render(request, 'serviceprovider/providerdetails.html', {'sprovider': sprovider})

def spOrderDetails(request, serviceprovider_id):
    sprovider = get_object_or_404(Service, pk=serviceprovider_id)
    # global sp 
    # sp = sprovider.serviceProviderId
    alpha = 2
    alpha = alpha**2
    all_orders = Orders.objects.all().filter(orderType=sprovider.serviceProviderType, fulfilled=False)
    all_orders = all_orders.annotate(result=(F('latitude')-sprovider.latitude)**2+(F('longitude')-sprovider.longitude)**2).filter(result__lt=alpha)
    context= {'allorders': all_orders, 'sprovider':sprovider.serviceProviderId, 'sprovidername':sprovider.serviceProviderName}
    return render(request, 'serviceprovider/odlist.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                # all_orders = Orders.objects.all()
                # context= {'allorders': all_orders}
                # return render(request, 'serviceprovider/orderlist.html', context)
                print(user.username)
                sprovider = get_object_or_404(Service, serviceProviderName=user.username)
                return render(request, 'serviceprovider/providerdetails.html', {'sprovider': sprovider})
                # return render(request, 'serviceprovider/serviceprovider/orderlist', {'albums': all_order})
            else:
                return render(request, 'serviceprovider/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'serviceprovider/login.html', {'error_message': 'Invalid login'})
    return render(request, 'serviceprovider/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                # albums = Album.objects.filter(user=request.user)
                # return render(request, 'serviceprovider/index.html', {'albums': albums})
    context = {
        "form": form,
    }
    return render(request, 'serviceprovider/registration.html', context)

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'serviceprovider/login.html', context)


@csrf_exempt
def save_state(request):
    print("hello")
    if request.method == 'POST':
        # title = request.POST.get('selectItems')
        # title = request.body.decode("utf-8") 
        selecteditems = json.loads(request.body.decode("utf-8"))["selectItems"]
        sname = json.loads(request.body.decode("utf-8"))["id"]
        servicep = get_object_or_404(Service, pk=sname)
        for i in selecteditems:
            order = get_object_or_404(Orders, pk=i)
            order.fulfilled=True
            order.save()

            # service = get_object_or_404(Service, pk=order.orderType)
            o=Order_Dispatch(service_id=servicep, order_id=order)
            o.save()
            # print(i)

        # print(selecteditems)
        # print(checked)
        # todo = Todo.objects.get(title=title)
        # todo.completed = checked
        # todo.save()
    return render(request, 'serviceprovider/providerdetails.html')

servicereg/website/serviceprovider/templates/serviceprovider/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

servicereg/website/serviceprovider/templates/serviceprovider/itemdetails.html
<h5>Item Id - {{ items.itemId }}</h5>
<h5>Order Id - {{ items.oId.orderId }}</h5>
<!-- <h5>Provider Id - {{ items.provider_id }}</h5> -->

servicereg/website/serviceprovider/templates/serviceprovider/login.html
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'serviceprovider:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'serviceprovider:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

servicereg/website/serviceprovider/templates/serviceprovider/odlist.html
<html>
    <head>
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        <script>
            function getvalues(){
                var selected = new Array();
                var sprovider = document.getElementById("sprovider");
                var chkbox = document.getElementById("t1");
                var selectchk = chkbox.getElementsByTagName("input");
                for(var i=0; i<selectchk.length; i++){
                    if(selectchk[i].checked){
                        selected.push(selectchk[i].value);
                    }
                }
                if(selected.length>0){
                    document.getElementById("displayvalues").innerHTML=selected;
                    console.log(selected);
                    console.log(sprovider.getAttribute("value"));
                    axios.post('/serviceprovider/save_state/', {
                        selectItems:selected,
                        id:sprovider.getAttribute("value")
                        })
                    .then((response)=>{
                        console.log(response);
                    }, 
                    (error)=>{console.error();});
                }                
            };
        </script>
    </head>
    {% load static %}
    <script src="{% static 'js/saveorder.js' %}" type="text/javascript"></script>
<body>
    {% if allorders %}
    <h3>Orders for Service Provider</h3>
    <h3 id="sprovider" value = "{{sprovider}}" >{{sprovider}}</h3>
    <h3>Service Provider Name : {{sprovidername}}</h3>
    <h3>Order List</h3>
    <table id="t1">
        <tr>
            <td>
                {% for order in allorders %}
                <li><input type="checkbox" id="{{ order.orderId }}" name="completed" value="{{ order.orderId }}" {% if order.completed is True %}
                        checked="checked" {% endif %}>
                    <a href="/serviceprovider/orderdetails/{{ order.orderId }}/"> {{ order.orderId }} </a> </li>
                {% endfor %}
            </td>
        </tr>
    </table>
    
    <input type="button" value="Dispatch" id="b1" onclick="getvalues()"></button>
    <b id = "displayvalues"></b>
    <!-- <h3>Dispatch</h3> -->
    {% else %}
    <h3>No orders to display</h3>
    {% endif %}
</body>

</html>

servicereg/website/serviceprovider/templates/serviceprovider/orderdetails.html
<!-- <html>
    <body>
            <h1>{{ order.orderId }}</h1>
            <h1>{{ order.customerId }}</h1>
            <h1>{{ order.fulfilled }}</h1>
    </body>
</html> -->

<!-- {{ order }} -->
<h3>Order Details</h3>
<h5>Order Id - {{ order.orderId }}</h5>
<h5>Customer Id - {{ order.customerId }}</h5>
<h5>Order Status - {{ order.fulfilled }}</h5>
<h5>Order Type - {{ order.orderType }}</h5>
<h5>Latitude - {{ order.latitude }}</h5>
<h5>Longitude - {{ order.longitude }}</h5>

{% if allitems %}
    <h3>Items</h3>
    <ul>
        {% for item in allitems %}
        <li><a href="/serviceprovider/orderdetails/itemdetails/{{ item.itemId }}/">  {{ item.itemId }} </a>   </li>
        {% endfor %}
    </ul>
    {% else %}
    <h3>No Items to display</h3>
{% endif %}

servicereg/website/serviceprovider/templates/serviceprovider/orderlist.html
<html>
    {% if allorders %}
        <h3>Orders</h3>
        <ul>
            {% for order in allorders %}
            <li><a href="/serviceprovider/orderdetails/{{ order.orderId }}/">  {{ order.orderId }} </a>   </li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>No orders to display</h3>
    {% endif %}
</html>

servicereg/website/serviceprovider/templates/serviceprovider/providerdetails.html
<h5>Service Provider Id - {{ sprovider.serviceProviderId }}</h5>
<h5>Service Provider Name - {{ sprovider.serviceProviderName }}</h5>
<h5>Service Provider Type - {{ sprovider.serviceProviderType }}</h5>
<h5>Latitude - {{ sprovider.latitude }}</h5>
<h5>Longitude - {{ sprovider.longitude }}</h5>
<h5>Logged In - {{ sprovider.loggedIn }}</h5>

<li><a href="/serviceprovider/sporderdetails/{{ sprovider.serviceProviderId }}/">  View Orders </a>   </li>

servicereg/website/serviceprovider/templates/serviceprovider/registration.html
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'serviceprovider/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'serviceprovider:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

servicereg/website/serviceprovider/templates/serviceprovider/sysscreen.html
<h1>
    Orders have been dispatched
<h1>